test

diff --git a/.github/workflows/easemlci.yml b/.github/workflows/easemlci.yml
--- a/.github/workflows/easemlci.yml
+++ b/.github/workflows/easemlci.yml
@@ -58,5 +58,9 @@ jobs:
 
             - name: Eval CI Test
               run: |
-                echo "HELLO"
-                jq -r '.name'
+                if [ $(jq .fail_type ./run_statistics.json) -eq "0" ]; then
+                   echo "Your model passed";
+                else
+                   echo "Your model failed";
+                   exit 1
+                fi
