test

diff --git a/.github/workflows/easemlci.yml b/.github/workflows/easemlci.yml
--- a/.github/workflows/easemlci.yml
+++ b/.github/workflows/easemlci.yml
@@ -46,19 +46,28 @@ jobs:
                 echo "Adding decryption and encryption keys"
                 mkdir -p $HOME/.easeml/keys
                 
-                git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
-                git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
                 echo ${{ secrets.B64_EASEML_PRIV }} | base64 -d > $HOME/.easeml/keys/easeml_priv.asc
                 echo ${{ secrets.B64_EASEML_PUB }} | base64 -d > $HOME/.easeml/keys/easeml_pub.asc
 
             - name: Run CI Test
-              run: |               
+              run: |
+                # Set identity for commits
+                git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
+                git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
+                
                 # Calling the ci runner
                 easeml_cicd_runner ${GITHUB_ACTOR} ${{ secrets.GITHUB_TOKEN }} ${GITHUB_REPOSITORY} ${GITHUB_SHA} ${GITHUB_REF_NAME} -g
 
             - name: Eval CI Test
               run: |
-                if [ $(jq .fail_type ./run_statistics.json) -eq "0" ]; then
+                FILE=./run_statistics.json
+                if [ -f "$FILE" ]; then
+                    echo "Results exist."
+                else 
+                    echo "Unable to find test results."
+                    exit 1
+                fi
+                if [ $(jq .fail_type $FILE) -eq "0" ]; then
                    echo "Your model passed";
                 else
                    echo "Your model failed";
